"""add transport models

Revision ID: a7fc4adfa11c
Revises: 9a4c7e877b84
Create Date: 2026-04-12 07:21:09.302793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7fc4adfa11c'
down_revision: Union[str, Sequence[str], None] = '9a4c7e877b84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('licence', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('aadhar_front', sa.String(), nullable=True),
    sa.Column('aadhar_back', sa.String(), nullable=True),
    sa.Column('licence_photo', sa.String(), nullable=True),
    sa.Column('pan_card_photo', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('owners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('pan_number', sa.String(), nullable=True),
    sa.Column('pan_image', sa.String(), nullable=True),
    sa.Column('aadhar_front', sa.String(), nullable=True),
    sa.Column('aadhar_back', sa.String(), nullable=True),
    sa.Column('account_number', sa.String(), nullable=True),
    sa.Column('ifsc_code', sa.String(), nullable=True),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trade_name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('pincode', sa.String(), nullable=True),
    sa.Column('gst_number', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parties_gst_number'), 'parties', ['gst_number'], unique=True)
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_number', sa.String(), nullable=True),
    sa.Column('loading_weight', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purchase_price', sa.String(), nullable=True),
    sa.Column('rc_image', sa.String(), nullable=True),
    sa.Column('insurance_expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('puc_expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fitness_expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tax_expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('permit_expiry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_service_due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['owners.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicles_vehicle_number'), 'vehicles', ['vehicle_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vehicles_vehicle_number'), table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_parties_gst_number'), table_name='parties')
    op.drop_table('parties')
    op.drop_table('owners')
    op.drop_table('drivers')
    # ### end Alembic commands ###
