"""updated user field

Revision ID: b03d2a8f2476
Revises: 1c4f8de56456
Create Date: 2026-04-08 22:01:33.924012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b03d2a8f2476'
down_revision: Union[str, Sequence[str], None] = '1c4f8de56456'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_agent', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_owner', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_driver', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_column('users', 'is_driver')
    op.drop_column('users', 'is_owner')
    op.drop_column('users', 'is_agent')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
